services:
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ai1_business_erp_db
      MYSQL_ROOT_PASSWORD: hello123 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge

